<a href="https://colab.research.google.com/github/harshjoshi23/ANN/blob/main/Ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# predictiong a binary output classificatiion prob

import numpy as np
import matplotlib as plt
import pandas as pd
import seaborn as sns 
plt.rcParams['figure.figsize'] = (15, 5)
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer
from sklearn.feature_selection import VarianceThreshold
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, MinMaxScaler

from sklearn.utils import class_weight
from sklearn.feature_selection import SelectKBest, chi2, RFECV, SelectFromModel
from sklearn.compose import ColumnTransformer, make_column_transformer

from keras.models import load_model
from keras.layers import Dense
from keras.models import load_model




In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Data Reading and Analysis 

In [3]:
# reading the DF 
df = pd.read_csv('/content/drive/MyDrive/Collabdf/Churn_Modelling.csv')

In [4]:
df.head(10)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0
5          6    15574012       Chu  ...               0       149756.71      1
6          7    15592531  Bartlett  ...               1        10062.80      0
7          8    15656148    Obinna  ...               0       119346.88      1
8          9    15792365        He  ...               1        74940.50      0
9         10    15592389        H?  ...               1        71725.73      0

[10 rows x 14 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


No need of null imputation and no date coloum present

In [45]:
dfcopy = df.copy()

In [46]:
df['Exited'].unique()

array([1, 0])

### Feature Engineering and selection

In [47]:
dfcopy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


Not seeing much features right now

In [48]:
f_features = [
            'Geography','Gender', 'Tenure','Age','Tenure','Balance','NumOfProducts','NumOfProducts','HasCrCard','EstimatedSalary','IsActiveMember'
]

In [49]:
X = dfcopy[f_features] # save
y = dfcopy['Exited']

In [50]:
X.head(1)

Geography  Gender  Tenure  ...  HasCrCard  EstimatedSalary  IsActiveMember
0    France  Female       2  ...          1        101348.88               1

[1 rows x 11 columns]

In [51]:
categorical_features = ['Geography','Gender']


## Encodig Our Data 

In [52]:
labelencoder_X = LabelEncoder()
# X['Geography'] =  labelencoder_X.fit_transform(X['Geography'])
X['Gender'] = labelencoder_X.fit_transform(X['Gender'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [53]:
X.shape

(10000, 11)

In [54]:
X.head(1) 

Geography  Gender  Tenure  ...  HasCrCard  EstimatedSalary  IsActiveMember
0    France       0       2  ...          1        101348.88               1

[1 rows x 11 columns]

In [15]:
# ohe=pd.get_dummies(X['Geography'])
# ohe

In [ ]:
break

In [55]:
from sklearn.preprocessing import LabelBinarizer


In [56]:
X = LabelBinarizer().fit_transform(df.Geography)


In [16]:
# ct = ColumnTransformer([("Geography", OneHotEncoder(), [])], remainder = 'passthrough')
# X = ct.fit_transform(X)

In [57]:
X

array([[1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       ...,
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0]])

In [17]:
# onehotencoder = OneHotEncoder(categorical_features = ['Geography'])
# X = onehotencoder.fir_transform(X).toarray()


## Train Test Split

In [18]:
X = X[:, 1: ]

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25,random_state=1)



In [20]:
display(X_train.shape )
display(X_test.shape )
display(y_train.shape )
display(y_test.shape )


(7500, 12)

(2500, 12)

(7500,)

(2500,)

In [21]:
from  sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [22]:
import keras
from keras.layers import Dense
from keras.models import Sequential



In [23]:
classifier = Sequential()


## Adding Hidden layers

### Adding the first Hidden Layer

Step 1 Randomly intitialize the weight of node to small no By Dense 
<br>
Step 2 Each feature goes to the neural network 
<br>
Step 3 We will use 

*   Rectifier   hidden layer
*   Sigmoidal - op layer 

Step 4 Compare Predicted Results to actual results. Measure the generated error.

Step 5 Back propogation from right to left, the error rate decides by how much we should update the weights.

Step 6 Repeat 1 to 5 batch or one by one 

Step 7 When the whole training set passes through Ann that makes an epoch. Redo more epochs.




### Using Schostic gradient descent 

In [24]:
# Add 1st hidden layer 
#using add method
# All the hyper parameters are defined inside the dense function
'''

output_dim - no of nodes we want to add in hidden layer
How many nodes to add - depends 
No of nodes in hidden = avg of (input and output layer)
or , 
do hyper parameter tuning 

'''

classifier.add(Dense(6, kernel_initializer='he_uniform', activation='relu'))
# unoform fuction is used to distribute weights uniformly 

''' Activation Functions 
Rectifier - hidden layer
Sigmoidal - op layer '''

# input dim par  no of nodes in input layer, i.e. no of ind variabes 
'''because ann is only initialze so it don't know wich layer is input layer 
but we only specifeid for 1st one'''

"because ann is only initialze so it don't know wich layer is input layer \nbut we only specifeid for 1st one"

### Adding second Hidden layer 

In [25]:
classifier.add(Dense(6, kernel_initializer='he_uniform', activation='relu'))


### Adding The output layer

In [26]:
classifier.add(Dense(1, kernel_initializer='he_uniform', activation='sigmoid'))
#we are using our activation function 
# binary outcome 1 mode 
'''we need prob for outcome so we need sigmoidal not relur 
    sigmoidal fn is eart to prob 
'''

'''if our outcome is not binary so we need to input 3 if we have 3 catagory 
and act fn is softmax and is kind of sigmoidal used for more than 2 catogeries'''


'if our outcome is not binary so we need to input 3 if we have 3 catagory \nand act fn is softmax and is kind of sigmoidal used for more than 2 catogeries'

## Compile our ann 

Applying stochastic gradient descent in ann

In [29]:
'''
def compile(optimizer='rmsprop', loss=None, metrics=None, loss_weights=None, weighted_metrics=None, run_eagerly=None, steps_per_execution=None, **kwargs)
Configures the model for training.

'''
# in optimizer we add Stochaztic 
# loss  corrospond to loss fn in Adam method 
'''
        specify a loss fn to find optimal weights 
        Same for a logesic regression 
            loss funtion is going to be a log function i.e. the log loss
    '''
# accuracy critarian  
'''
        metrics = ['accuracy']
    '''

'''
Example:

model.compile(optimizer=tf.keras.optimizer.Adam(learning_rate=1e-3),
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=[tf.keras.metrics.BinaryAccuracy(),
                       tf.keras.metrics.FalseNegatives()])


                       '''

'\nExample:\n\nmodel.compile(optimizer=tf.keras.optimizer.Adam(learning_rate=1e-3),\n              loss=tf.keras.losses.BinaryCrossentropy(),\n              metrics=[tf.keras.metrics.BinaryAccuracy(),\n                       tf.keras.metrics.FalseNegatives()])\n\n\n                       '

In [30]:
'''

adam   BinaryCrossentropy  catagoricalCrossentropy(for more tan 2)

'''

'\n\nadam   BinaryCrossentropy  catagoricalCrossentropy(for more tan 2)\n\n'

In [31]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

## Choosing No of Ephocs 
No of times we want to train our ann on the whole training set 
and 
how it's accuracy is increased

In [ ]:
# Fit ANN to training set using fit method 
# batch size = dividing into baches 
# epochs = No of epoches 
classifier.fit(X_train,y_train,batch_size= 10 , epochs= 100 )

## Making prediction on test set 

In [33]:
y_pred = classifier.predict(X_test)



In [67]:
from sklearn.metrics import classification_report


In [71]:
# # model_lgb.fit(x_train, y_train, eval_set = [(x_test, y_test)], verbose = 0)
# # display(classifier.plot_importance(classifier))
# ### Classification Report - Train
# print(classification_report(y_train, classifier.predict(X_trai n)))

# ### Classification Report - Test/Validation
# print(classification_report(y_test, y_pred))

In [65]:
y_pred

array([[0.02371079],
       [0.10560134],
       [0.03561652],
       ...,
       [0.24669164],
       [0.38288525],
       [0.12340495]], dtype=float32)

In [72]:
# cm = confusion_matrix(y_test, y_pred, output_dict=True)
# print("\n***** Test *****")
# print(cm)

In [58]:
# from sklearn.metrics import confusion_matrix
# cm = confusion_matrix(y_test, y_pred)
# cm

In [38]:
y_test

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
6955    0
557     1
2455    1
3920    0
6405    0
Name: Exited, Length: 2500, dtype: int64